### ISSUE TITLE
You cannot access the lua package while targeting cpp (for lua.Boot)

### ISSUE THREAD

**Issue by Royal806** [MattTuttle/hx-lua#6]
C:\HaxeToolkit\haxe\std/haxe/io/Bytes.hx:325: characters 9-17 : You cannot access the lua package while targeting cpp (for lua.Boot)

I get this error when attempting to build cpp or neko targets.

**Comment by gmisail** [comment]
There is a Lua target for Haxe, so you should download the library as something other than lua. When you install the library using haxelib _(haxelib git lua ...)_ , you should use a name like _hxlua_ instead of lua. For example, _haxelib git hxlua git-repo..._. In the build.hxml file, you should replace the name of the library, _(-lib lua)_ to the name you chose earlier.

**Comment by MattTuttle** [comment]
Good point. This was written before the lua target existed.
